import type { Metadata } from "next";
// 1. Import Noto_Sans_Thai เพิ่มเข้ามา
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. ตั้งค่า Noto Sans Thai (เราจะใช้เป็น variable เหมือนกัน)
const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["latin", "thai"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  // 3. อัปเดต Title
  title: "Book Request Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 4. เพิ่มตัวแปรฟอนต์ 'notoSansThai.variable' เข้าไปใน body */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansThai.variable} antialiased`}
      >
        {/*
          [แก้ไข] นี่คือขั้นตอนที่ 7 ครับ
          เราหุ้ม {children} (ทั้งเว็บ) ด้วย AuthProvider
          เพื่อให้ทุกหน้าสามารถเช็กสถานะ Login ได้
        */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

